# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    # Other tool versions can also be specified here if needed

sphinx:
   configuration: docs/conf.py

python:
   install:
     - method: pip
       path: .
       extras: [dev]  # specifying to install the 'dev' extra dependencies

# Other configurations can continue below
